

on:
  push:
    branches: main
  pull_request:
    branches: main

name: Build Site

jobs:
   build-website:
     runs-on: ubuntu-latest
     timeout-minutes: 30
     env:
       GITHUB_PAT: ${{ secrets.SUPERSECRET }}
     steps:
       - name: Checkout repo
         uses: actions/checkout@v4
         with:
           submodules: recursive
  
       - name: Set up R
         uses: r-lib/actions/setup-r@v2
         with:
           use-public-rspm: true
  
      - name: Setup pandoc
         uses: r-lib/actions/setup-pandoc@v2
          with:
            pandoc-version: '2.12'
  
       - name: Setup Hugo
         uses: peaceiris/actions-hugo@v2
         with:
           hugo-version: '0.112.5'
           extended: true
  
       - name: Set up renv
         uses: r-lib/actions/setup-renv@v2
         with:
           cache-version: 2
        
       - name: Manually install packages 
         run: |
           R -e 'install.packages(c("blogdown", "rmarkdown")'
  
       - name: Manually build site
         run: |
           R -e 'blogdown::build_site()'
            
        # - name: Deploy 🚀
        #   if: github.event_name != 'pull_request'
        #   uses: JamesIves/github-pages-deploy-action@4.1.7
        #   with:
        #     branch: gh-pages # The branch the action should deploy to.
        #     folder: public # The folder the action should deploy.
            